- hosts: all
  vars:
    homebrew_taps:
      - caskroom/cask
 
    homebrew_cask_packages:
      - name: appcleaner
      - name: docker
      - name: evernote
      - name: google-chrome
      - name: slack
      - name: sourcetree
      - name: spotify
      - name: vagrant
      - name: virtualbox
      - name: visual-studio-code
 
    homebrew_packages:
      - name: awscli
      - name: ansible
      - name: docker
      - name: git
      - name: go
      - name: pyenv
      - name: python
      - name: python3
      - name: tig
      - name: tmux
      - name: zsh
 
  tasks:
    - name: homebrew update
      homebrew:
        update_homebrew: yes
 
    - name: homebrew tap
      homebrew_tap:
        name: '{{ item }}'
        state: present
      with_items: '{{ homebrew_taps }}'
 
    - name: homebrew cask packages install
      homebrew_cask: name={{ item.name }} state=installed
      environment:
        HOMEBREW_CASK_OPTS: "--appdir=/Applications"
      with_items: '{{ homebrew_cask_packages }}'
 
    - name: homebrew packages install
      homebrew:
        name: '{{ item.name }}'
        state: '{{ item.state | default("present") }}'
      with_items: '{{ homebrew_packages }}'
