- hosts: all
  vars:
    homebrew_taps:
      - homebrew/cask
 
    homebrew_cask_packages:
      - name: android-file-transfer
      - name: android-studio
      - name: appcleaner
      - name: bettertouchtool
      - name: docker
      - name: gpg-suite
      - name: iterm2
      - name: keybase
      - name: sequel-pro
      - name: sketch
      - name: skype
      - name: slack
      - name: sourcetree
      - name: spotify
      - name: telegram
      - name: vagrant
      - name: virtualbox
      - name: visual-studio-code

    homebrew_packages:
      - name: awscli
      - name: ansible
	  - name: cmake
      - name: direnv
      - name: docker
      - name: emacs
      - name: git
      - name: go
      - name: fzf
      - name: jq
      - name: nvm
      - name: pyenv
      - name: python
      - name: python3
      - name: tree
      - name: zsh

  tasks:
    - name: homebrew update
      homebrew:
        update_homebrew: yes

    - name: homebrew tap
      homebrew_tap:
        name: '{{ item }}'
        state: present
      with_items: '{{ homebrew_taps }}'

    - name: homebrew cask packages install
      homebrew_cask: name={{ item.name }} state=installed
      environment:
        HOMEBREW_CASK_OPTS: "--appdir=/Applications"
      with_items: '{{ homebrew_cask_packages }}'

    - name: homebrew packages install
      homebrew:
        name: '{{ item.name }}'
        state: '{{ item.state | default("present") }}'
      with_items: '{{ homebrew_packages }}'
